version: 2

sources:
  - name: staging
    database: dtc-de-course-374916
    schema: trips_data

    tables:
      - name: green_data
      - name: yellow_data
      - name: fhv_tripdata_partitioned
